name: foodcalc
channels: 
  - conda-forge
  - anaconda
  - defaults
dependencies: 
  - python >= 3.10
  - pandas >= 2.1
  - requests >= 2.18
  - matplotlib
  - pdbpp
  - country_converter >= 1.0
  - black >= 22.8
  - ipython
  - jupyterlab=3.*
  - jupytext
  - pynvim
  - ipykernel
